### ISSUE TITLE
Julia icon

### ISSUE THREAD

**Issue by yjunechoe** [EmilHvitfeldt/quarto-revealjs-codewindow#1]
Thanks for the extension - This is really awesome!

Please add the juilia (dots) logo for `.jl` class :) - https://github.com/JuliaLang/julia-logo-graphics/blob/master/images/julia-dots.svg

![image](https://github.com/EmilHvitfeldt/quarto-revealjs-codewindow/assets/52832839/c6df9027-5c5a-461f-b3c7-cf3fb360dccb)

**Comment by EmilHvitfeldt** [comment]
Added in https://github.com/EmilHvitfeldt/quarto-revealjs-codewindow/commit/3d49aa576a3dae78d75593f67062455bd436fd2e
