### ISSUE TITLE
bash icon

### ISSUE THREAD

**Issue by lpembleton** [EmilHvitfeldt/quarto-revealjs-codewindow#7]
bash or terminal icon would be fantastic when sharing Linux code snippets.

**Comment by EmilHvitfeldt** [comment]
Do you have a favorite icon you would like me to use? (no gradients)

**Comment by lpembleton** [comment]
I think the terminal icon would be generic enough that it could cover both shell and bash code snippets. 
Maybe an icon like https://pictogrammers.com/library/mdi/icon/console/ or https://icon-icons.com/icon/terminal-shell/143501
Not sure if you have a better source for that style of icon?
Would be fantastic in an orange colour (#FF7043)
Thanks!
